import random

#GENERATE A RANDOM NUMBER BETWEEN 1 AND 10
#print(random.randint(1,10))

#PICK A RANDOM CHOICE FROM A LIST.
print("FREE GAMEPASS REWARD:", random.choice(["MINECRAFT","SEA OF THIEVES","ARK:SURVIVAL EVOLVED"]))